"""
SHL Individual Test Solutions Catalog
Compiled from https://www.shl.com/products/product-catalog/ (type=1, Individual Test Solutions)

Test Type codes:
  A = Ability & Aptitude
  B = Biodata & Situational Judgement  
  C = Competencies
  D = Development & 360
  E = Assessment Exercises
  K = Knowledge & Skills
  P = Personality & Behavior
  S = Simulations
"""

CATALOG = [
    # ─── Cognitive / Ability ───────────────────────────────────────────────
    {
        "name": "Verify Numerical Reasoning",
        "url": "https://www.shl.com/products/product-catalog/view/verify-numerical-reasoning/",
        "test_types": ["A"],
        "test_type": "A",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Measures the ability to understand and critically evaluate numerical data presented in tables and graphs. Suitable for professional and graduate-level roles.",
        "job_levels": ["Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Business", "Information Technology", "Sales"],
        "keywords": ["numerical", "data", "analysis", "quantitative", "math", "finance", "analytical", "reasoning"],
    },
    {
        "name": "Verify Verbal Reasoning",
        "url": "https://www.shl.com/products/product-catalog/view/verify-verbal-reasoning/",
        "test_types": ["A"],
        "test_type": "A",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Measures the ability to understand and evaluate written information and make logical inferences. Used widely for roles requiring communication and comprehension skills.",
        "job_levels": ["Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Business", "Information Technology"],
        "keywords": ["verbal", "comprehension", "reading", "communication", "language", "writing", "reasoning"],
    },
    {
        "name": "Verify Inductive Reasoning",
        "url": "https://www.shl.com/products/product-catalog/view/verify-inductive-reasoning/",
        "test_types": ["A"],
        "test_type": "A",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Measures the ability to identify underlying patterns in information and predict outcomes. Suitable for roles requiring abstract thinking and problem-solving.",
        "job_levels": ["Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Business", "Information Technology"],
        "keywords": ["inductive", "abstract", "pattern", "logical", "problem solving", "reasoning", "analytical"],
    },
    {
        "name": "Verify Deductive Reasoning",
        "url": "https://www.shl.com/products/product-catalog/view/verify-deductive-reasoning/",
        "test_types": ["A"],
        "test_type": "A",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Measures the ability to draw logical conclusions from given information. Suitable for roles involving complex analytical tasks.",
        "job_levels": ["Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Business", "Information Technology"],
        "keywords": ["deductive", "logical", "reasoning", "problem solving", "analytical", "critical thinking"],
    },
    {
        "name": "SHL Verify Interactive G+",
        "url": "https://www.shl.com/products/product-catalog/view/shl-verify-interactive-g/",
        "test_types": ["A"],
        "test_type": "A",
        "remote_testing": True,
        "adaptive_irt": True,
        "description": "Tests general cognitive ability (g factor) with interactive drag-and-drop questions covering deductive, inductive, and numerical reasoning. Mobile-optimized. 36-minute test.",
        "job_levels": ["Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Business", "Information Technology", "Sales"],
        "keywords": ["cognitive", "general ability", "g factor", "reasoning", "analytical", "problem solving", "interactive", "mobile"],
    },
    {
        "name": "Verify Interactive - Numerical Reasoning",
        "url": "https://www.shl.com/products/product-catalog/view/verify-interactive-numerical-reasoning/",
        "test_types": ["A"],
        "test_type": "A",
        "remote_testing": True,
        "adaptive_irt": True,
        "description": "Interactive, mobile-first numerical reasoning test using drag-and-drop questions. Measures ability to interpret tables and graphs.",
        "job_levels": ["Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Business", "Information Technology"],
        "keywords": ["numerical", "interactive", "mobile", "data", "quantitative", "math", "reasoning"],
    },
    {
        "name": "Verify Interactive - Inductive Reasoning",
        "url": "https://www.shl.com/products/product-catalog/view/verify-interactive-inductive-reasoning/",
        "test_types": ["A"],
        "test_type": "A",
        "remote_testing": True,
        "adaptive_irt": True,
        "description": "Interactive, mobile-first inductive reasoning test using drag-and-drop. Measures abstract pattern recognition.",
        "job_levels": ["Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Business", "Information Technology"],
        "keywords": ["inductive", "abstract", "pattern", "interactive", "mobile", "reasoning"],
    },
    {
        "name": "Verify Interactive - Deductive Reasoning",
        "url": "https://www.shl.com/products/product-catalog/view/verify-interactive-deductive-reasoning/",
        "test_types": ["A"],
        "test_type": "A",
        "remote_testing": True,
        "adaptive_irt": True,
        "description": "Interactive, mobile-first deductive reasoning test using drag-and-drop. Measures logical deduction from given premises.",
        "job_levels": ["Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Business", "Information Technology"],
        "keywords": ["deductive", "logical", "interactive", "mobile", "reasoning"],
    },
    {
        "name": "Verify G+",
        "url": "https://www.shl.com/products/product-catalog/view/verify-g-plus/",
        "test_types": ["A"],
        "test_type": "A",
        "remote_testing": True,
        "adaptive_irt": True,
        "description": "Adaptive measure of general cognitive ability (g) combining numerical, verbal, and inductive reasoning. Ideal for professional and graduate hiring.",
        "job_levels": ["Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Business", "Information Technology"],
        "keywords": ["cognitive", "general ability", "adaptive", "reasoning", "analytical"],
    },

    # ─── Personality & Behavior ────────────────────────────────────────────
    {
        "name": "Occupational Personality Questionnaire OPQ32r",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/occupational-personality-questionnaire-opq32r/",
        "test_types": ["P"],
        "test_type": "P",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "The SHL OPQ32r measures 32 personality characteristics related to workplace performance. Internationally recognized with 90+ validation studies across 20 countries. Provides a clear framework for understanding personality's impact on job performance.",
        "job_levels": ["Director", "Executive", "Front Line Manager", "General Population", "Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor", "Supervisor"],
        "job_families": ["Business", "Information Technology", "Sales", "Contact Center"],
        "keywords": ["personality", "behavior", "traits", "OPQ", "occupational", "leadership", "management", "culture fit", "teamwork", "communication"],
    },
    {
        "name": "Occupational Personality Questionnaire OPQ32n",
        "url": "https://www.shl.com/products/product-catalog/view/occupational-personality-questionnaire-opq32n/",
        "test_types": ["P"],
        "test_type": "P",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Normative version of OPQ32 measuring 32 personality characteristics via Likert-scale responses. Suitable for development contexts.",
        "job_levels": ["Director", "Executive", "Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Business", "Information Technology"],
        "keywords": ["personality", "behavior", "OPQ", "normative", "development", "traits"],
    },
    {
        "name": "Motivational Questionnaire MQM5",
        "url": "https://www.shl.com/products/product-catalog/view/motivational-questionnaire-mqm5/",
        "test_types": ["P"],
        "test_type": "P",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Measures 18 motivational factors to identify what energizes and drives an individual at work. 150 questions taking approximately 25 minutes.",
        "job_levels": ["Director", "Executive", "Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor", "Supervisor"],
        "job_families": ["Business", "Information Technology"],
        "keywords": ["motivation", "engagement", "drive", "values", "culture", "retention", "MQ"],
    },
    {
        "name": "Global Skills Assessment (GSA)",
        "url": "https://www.shl.com/products/product-catalog/view/global-skills-assessment/",
        "test_types": ["P", "A", "B"],
        "test_type": "P",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Comprehensive assessment measuring cognitive ability, personality, and workplace skills in a single session. Designed for global talent acquisition.",
        "job_levels": ["Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Business", "Information Technology", "Sales"],
        "keywords": ["global", "skills", "cognitive", "personality", "comprehensive", "all-in-one", "GSA"],
    },
    {
        "name": "Global Skills Development Report",
        "url": "https://www.shl.com/products/product-catalog/view/global-skills-development-report/",
        "test_types": ["A", "E", "B", "C", "D", "P"],
        "test_type": "D",
        "remote_testing": False,
        "adaptive_irt": False,
        "description": "Development report based on personality and ability data providing actionable insights for skills growth. Used in talent management contexts.",
        "job_levels": ["Director", "Executive", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Business"],
        "keywords": ["development", "skills", "report", "growth", "talent management", "learning"],
    },

    # ─── Biodata & SJT ─────────────────────────────────────────────────────
    {
        "name": "Sales Achievement Predictor",
        "url": "https://www.shl.com/products/product-catalog/view/sales-achievement-predictor/",
        "test_types": ["B", "P"],
        "test_type": "B",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Assesses sales personality traits and biodata predictors of sales achievement. Suitable for all levels of sales roles.",
        "job_levels": ["Entry-Level", "Mid-Professional", "Professional Individual Contributor", "Supervisor"],
        "job_families": ["Sales"],
        "keywords": ["sales", "selling", "achievement", "revenue", "customer", "B2B", "B2C"],
    },
    {
        "name": "Customer Contact Styles Questionnaire",
        "url": "https://www.shl.com/products/product-catalog/view/customer-contact-styles-questionnaire/",
        "test_types": ["B", "P"],
        "test_type": "B",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Measures behavioral styles relevant to customer-facing roles. Assesses ability to build rapport and manage customer interactions.",
        "job_levels": ["Entry-Level", "Front Line Manager", "Mid-Professional", "Professional Individual Contributor", "Supervisor"],
        "job_families": ["Contact Center", "Customer Service", "Sales"],
        "keywords": ["customer service", "contact center", "rapport", "communication", "empathy", "CX"],
    },

    # ─── Technical / Knowledge Tests ─────────────────────────────────────
    {
        "name": "Java 8 (New)",
        "url": "https://www.shl.com/products/product-catalog/view/java-8-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of Java 8 features including streams, lambda expressions, functional interfaces, and new date/time API.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["Java", "Java 8", "programming", "software development", "developer", "backend", "coding"],
    },
    {
        "name": "Core Java (Advanced Level)",
        "url": "https://www.shl.com/products/product-catalog/view/core-java-advanced-level-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Advanced multi-choice test on core Java including OOP, concurrency, generics, and JVM internals.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["Java", "core Java", "OOP", "concurrency", "senior", "advanced", "developer", "backend"],
    },
    {
        "name": "Python (New)",
        "url": "https://www.shl.com/products/product-catalog/view/python-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of Python programming including syntax, data structures, OOP, and standard library.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["Python", "programming", "scripting", "data science", "developer", "backend", "automation"],
    },
    {
        "name": "JavaScript (New)",
        "url": "https://www.shl.com/products/product-catalog/view/javascript-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of JavaScript including ES6+, DOM manipulation, closures, and async programming.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["JavaScript", "JS", "frontend", "web development", "developer", "React", "Node", "programming"],
    },
    {
        "name": "SQL (New)",
        "url": "https://www.shl.com/products/product-catalog/view/sql-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of SQL including querying, joins, aggregations, and database design.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["SQL", "database", "queries", "data", "analytics", "backend", "data analyst"],
    },
    {
        "name": "C++ (New)",
        "url": "https://www.shl.com/products/product-catalog/view/cplusplus-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of C++ including OOP, memory management, STL, and templates.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["C++", "programming", "systems", "embedded", "developer", "backend"],
    },
    {
        "name": "C# (New)",
        "url": "https://www.shl.com/products/product-catalog/view/c-sharp-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of C# including .NET, OOP, LINQ, and async programming.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["C#", ".NET", "programming", "Microsoft", "developer", "backend", "enterprise"],
    },
    {
        "name": ".NET Framework 4.5",
        "url": "https://www.shl.com/products/product-catalog/view/net-framework-4-5/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of .NET Framework 4.5 including CLR, libraries, and application development.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": [".NET", "Microsoft", "framework", "developer", "backend", "enterprise"],
    },
    {
        "name": ".NET MVC (New)",
        "url": "https://www.shl.com/products/product-catalog/view/net-mvc-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of ASP.NET MVC including routing, controllers, views, and model binding.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": [".NET", "MVC", "ASP.NET", "web", "developer", "backend", "Microsoft"],
    },
    {
        "name": "Spring (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/spring-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of Spring core, AOP, IOC container and transactions.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["Spring", "Java", "Spring Boot", "backend", "developer", "enterprise", "microservices"],
    },
    {
        "name": "Agile Software Development",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/agile-software-development/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of agile methodology, scrum, feature driven development, and incremental/iterative development processes.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["agile", "scrum", "sprint", "software development", "methodology", "project management", "developer"],
    },
    {
        "name": "Manual Testing (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/manual-testing-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of software testing lifecycle, testing tools and techniques, test case design, and test reports.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["testing", "QA", "quality assurance", "test cases", "software testing", "manual testing"],
    },
    {
        "name": "Selenium (New)",
        "url": "https://www.shl.com/products/product-catalog/view/selenium-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of Selenium WebDriver for automated web testing.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["Selenium", "automation testing", "QA", "test automation", "web testing", "developer"],
    },
    {
        "name": "Angular (New)",
        "url": "https://www.shl.com/products/product-catalog/view/angular-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of Angular framework including components, directives, services, and routing.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["Angular", "frontend", "TypeScript", "web development", "developer", "JavaScript"],
    },
    {
        "name": "React (New)",
        "url": "https://www.shl.com/products/product-catalog/view/react-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of React including components, hooks, state management, and JSX.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["React", "ReactJS", "frontend", "JavaScript", "web development", "developer", "UI"],
    },
    {
        "name": "Node.js (New)",
        "url": "https://www.shl.com/products/product-catalog/view/node-js-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of Node.js including event loop, modules, npm, and Express.js.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["Node.js", "NodeJS", "backend", "JavaScript", "server-side", "developer", "API"],
    },
    {
        "name": "AWS (New)",
        "url": "https://www.shl.com/products/product-catalog/view/amazon-web-services-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of Amazon Web Services including EC2, S3, Lambda, and cloud architecture.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["AWS", "cloud", "Amazon", "DevOps", "infrastructure", "developer", "cloud architect"],
    },
    {
        "name": "Microsoft Azure (New)",
        "url": "https://www.shl.com/products/product-catalog/view/microsoft-azure-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of Microsoft Azure cloud services and architecture.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["Azure", "Microsoft", "cloud", "DevOps", "infrastructure", "developer"],
    },
    {
        "name": "DevOps (New)",
        "url": "https://www.shl.com/products/product-catalog/view/devops-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of DevOps practices including CI/CD, containerization, and infrastructure as code.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["DevOps", "CI/CD", "Docker", "Kubernetes", "infrastructure", "deployment", "automation", "cloud"],
    },
    {
        "name": "Docker (New)",
        "url": "https://www.shl.com/products/product-catalog/view/docker-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of Docker containerization including images, containers, Dockerfile, and Docker Compose.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["Docker", "containers", "DevOps", "containerization", "cloud", "developer"],
    },
    {
        "name": "Machine Learning (New)",
        "url": "https://www.shl.com/products/product-catalog/view/machine-learning-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of machine learning algorithms, model training, evaluation, and deployment.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["machine learning", "ML", "AI", "data science", "algorithms", "model", "developer"],
    },
    {
        "name": "Data Science (New)",
        "url": "https://www.shl.com/products/product-catalog/view/data-science-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of data science including statistics, Python, data wrangling, and model building.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["data science", "statistics", "Python", "analytics", "ML", "data analyst", "data scientist"],
    },
    {
        "name": "Cybersecurity (New)",
        "url": "https://www.shl.com/products/product-catalog/view/cybersecurity-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of cybersecurity including network security, vulnerabilities, encryption, and security practices.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["cybersecurity", "security", "network", "vulnerabilities", "encryption", "infosec"],
    },
    {
        "name": "Linux (New)",
        "url": "https://www.shl.com/products/product-catalog/view/linux-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of Linux operating system including commands, file system, permissions, and shell scripting.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["Linux", "Unix", "shell", "bash", "scripting", "systems", "DevOps", "developer"],
    },
    {
        "name": "Android (New)",
        "url": "https://www.shl.com/products/product-catalog/view/android-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of Android development including activities, fragments, SDK, and UI components.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["Android", "mobile", "Java", "Kotlin", "developer", "app development"],
    },
    {
        "name": "iOS (New)",
        "url": "https://www.shl.com/products/product-catalog/view/ios-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of iOS development including Swift, UIKit, Xcode, and Apple frameworks.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["iOS", "Swift", "Apple", "mobile", "developer", "app development", "Objective-C"],
    },
    {
        "name": "Swing (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/swing-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of components, containers, layouts and event handling in Swing.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["Swing", "Java", "GUI", "UI", "desktop", "developer"],
    },
    {
        "name": "ADO.NET (New)",
        "url": "https://www.shl.com/products/product-catalog/view/ado-net-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of ADO.NET for data access in .NET applications.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": [".NET", "ADO.NET", "database", "data access", "C#", "developer"],
    },
    {
        "name": "MS Excel (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/ms-excel-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring the ability to use MS Excel to maintain, organize, analyze, and present numeric data.",
        "job_levels": ["Entry-Level", "Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor", "Supervisor"],
        "job_families": ["Business", "Clerical"],
        "keywords": ["Excel", "spreadsheet", "Microsoft", "data analysis", "finance", "admin", "clerical"],
    },
    {
        "name": "MS Word (New)",
        "url": "https://www.shl.com/products/product-catalog/view/ms-word-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of MS Word for document creation and formatting.",
        "job_levels": ["Entry-Level", "Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Business", "Clerical"],
        "keywords": ["Word", "Microsoft", "documents", "formatting", "admin", "clerical", "office"],
    },
    {
        "name": "Accounts Payable (New)",
        "url": "https://www.shl.com/products/product-catalog/view/accounts-payable-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of accounts payable processes and procedures.",
        "job_levels": ["Entry-Level", "Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Business"],
        "keywords": ["accounts payable", "finance", "accounting", "AP", "bookkeeping"],
    },
    {
        "name": "Accounts Receivable (New)",
        "url": "https://www.shl.com/products/product-catalog/view/accounts-receivable-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of accounts receivable processes and procedures.",
        "job_levels": ["Entry-Level", "Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Business"],
        "keywords": ["accounts receivable", "finance", "accounting", "AR", "bookkeeping"],
    },

    # ─── Simulations ───────────────────────────────────────────────────────
    {
        "name": "Accounts Payable Simulation (New)",
        "url": "https://www.shl.com/products/product-catalog/view/accounts-payable-simulation-new/",
        "test_types": ["S"],
        "test_type": "S",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Simulation measuring practical accounts payable skills through realistic work tasks.",
        "job_levels": ["Entry-Level", "Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Business"],
        "keywords": ["accounts payable", "finance", "simulation", "accounting", "practical"],
    },
    {
        "name": "Accounts Receivable Simulation (New)",
        "url": "https://www.shl.com/products/product-catalog/view/accounts-receivable-simulation-new/",
        "test_types": ["S"],
        "test_type": "S",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Simulation measuring practical accounts receivable skills through realistic work tasks.",
        "job_levels": ["Entry-Level", "Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Business"],
        "keywords": ["accounts receivable", "finance", "simulation", "accounting", "practical"],
    },
    {
        "name": "Contact Center Simulation",
        "url": "https://www.shl.com/products/product-catalog/view/contact-center-simulation/",
        "test_types": ["S"],
        "test_type": "S",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Realistic simulation of contact center tasks measuring customer service skills, multitasking, and data entry accuracy.",
        "job_levels": ["Entry-Level", "Front Line Manager"],
        "job_families": ["Contact Center", "Customer Service"],
        "keywords": ["contact center", "call center", "customer service", "simulation", "CX", "support"],
    },

    # ─── Behavioral / SJT ─────────────────────────────────────────────────
    {
        "name": "Workplace English Language Test (WELT)",
        "url": "https://www.shl.com/products/product-catalog/view/workplace-english-language-test/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Assesses English language proficiency in workplace contexts including reading, listening, and comprehension.",
        "job_levels": ["Entry-Level", "Graduate", "Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Business", "Contact Center"],
        "keywords": ["English", "language", "communication", "proficiency", "bilingual", "global"],
    },
    {
        "name": "Supervisory Skills Questionnaire",
        "url": "https://www.shl.com/products/product-catalog/view/supervisory-skills-questionnaire/",
        "test_types": ["A", "B"],
        "test_type": "A",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Situational judgment test for supervisory roles assessing decision-making in people management and operational situations.",
        "job_levels": ["Front Line Manager", "Supervisor"],
        "job_families": ["Business"],
        "keywords": ["supervisor", "management", "leadership", "SJT", "situational", "team lead"],
    },
    {
        "name": "Management and Graduate Item Bank",
        "url": "https://www.shl.com/products/product-catalog/view/management-and-graduate-item-bank/",
        "test_types": ["A"],
        "test_type": "A",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Comprehensive item bank for building custom ability tests for management and graduate-level positions.",
        "job_levels": ["Graduate", "Manager"],
        "job_families": ["Business"],
        "keywords": ["management", "graduate", "cognitive", "ability", "custom"],
    },
    {
        "name": "Sales Representative SJT",
        "url": "https://www.shl.com/products/product-catalog/view/sales-representative-sjt/",
        "test_types": ["B"],
        "test_type": "B",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Situational judgment test for sales roles measuring responses to typical sales challenges and customer interactions.",
        "job_levels": ["Entry-Level", "Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Sales"],
        "keywords": ["sales", "SJT", "situational judgment", "customer", "selling"],
    },
    {
        "name": "OPQ Universal Competency Report 2.0",
        "url": "https://www.shl.com/products/product-catalog/view/opq-universal-competency-report-2-0/",
        "test_types": ["P"],
        "test_type": "P",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "OPQ-based report showing how personality impacts competencies across the Universal Competency Framework. Provides graphical scales for each competency.",
        "job_levels": ["Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor", "Supervisor", "Director", "Executive", "Front Line Manager"],
        "job_families": ["Business", "Information Technology"],
        "keywords": ["OPQ", "personality", "competencies", "UCF", "leadership", "report", "development"],
    },
    {
        "name": "OPQ Emotional Intelligence Report",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/opq-emotional-intelligence-report/",
        "test_types": ["P"],
        "test_type": "P",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "OPQ-based report exploring how a person manages feelings and relationships. Intended for development settings.",
        "job_levels": ["Director", "Executive", "Front Line Manager", "Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor", "Supervisor"],
        "job_families": ["Business"],
        "keywords": ["OPQ", "emotional intelligence", "EQ", "personality", "relationships", "development", "leadership"],
    },
    {
        "name": "OPQ Manager Report",
        "url": "https://www.shl.com/products/product-catalog/view/opq-manager-report/",
        "test_types": ["P"],
        "test_type": "P",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "OPQ report tailored for management roles showing personality's impact on key managerial competencies.",
        "job_levels": ["Director", "Executive", "Manager"],
        "job_families": ["Business"],
        "keywords": ["OPQ", "personality", "manager", "leadership", "management", "report", "executive"],
    },
    {
        "name": "OPQ Sales Report",
        "url": "https://www.shl.com/products/product-catalog/view/opq-sales-report/",
        "test_types": ["P"],
        "test_type": "P",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "OPQ-based report focused on sales competencies, showing personality traits relevant to sales performance.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor", "Supervisor"],
        "job_families": ["Sales"],
        "keywords": ["OPQ", "personality", "sales", "revenue", "selling", "report"],
    },
    # Additional IT/Tech tests
    {
        "name": "PHP (New)",
        "url": "https://www.shl.com/products/product-catalog/view/php-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of PHP including syntax, OOP, web development, and database interaction.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["PHP", "web development", "backend", "programming", "developer"],
    },
    {
        "name": "Ruby on Rails (New)",
        "url": "https://www.shl.com/products/product-catalog/view/ruby-on-rails-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of Ruby on Rails framework for web development.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["Ruby", "Rails", "web development", "backend", "programming", "developer"],
    },
    {
        "name": "Hadoop (New)",
        "url": "https://www.shl.com/products/product-catalog/view/hadoop-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of Hadoop ecosystem including HDFS, MapReduce, and big data processing.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["Hadoop", "big data", "HDFS", "MapReduce", "data engineering", "developer"],
    },
    {
        "name": "Spark (New)",
        "url": "https://www.shl.com/products/product-catalog/view/spark-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of Apache Spark for big data processing.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["Spark", "big data", "Apache", "data engineering", "Python", "Scala", "developer"],
    },
    {
        "name": "Scala (New)",
        "url": "https://www.shl.com/products/product-catalog/view/scala-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of Scala programming language including functional programming and JVM.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["Scala", "functional programming", "JVM", "big data", "developer"],
    },
    {
        "name": "Selenium Web Driver (New)",
        "url": "https://www.shl.com/products/product-catalog/view/selenium-web-driver-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of Selenium WebDriver for test automation.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["Selenium", "automation", "testing", "QA", "web testing", "Java", "Python"],
    },
    {
        "name": "Technology Professional 8.0 Solution",
        "url": "https://www.shl.com/products/product-catalog/view/technology-professional-8-0-solution/",
        "test_types": ["A", "B", "P"],
        "test_type": "A",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Pre-built assessment bundle for technology professional roles combining cognitive ability, personality, and behavior assessments.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Information Technology"],
        "keywords": ["technology", "IT", "software", "professional", "cognitive", "personality", "developer", "engineer"],
    },
    # Business/Finance
    {
        "name": "General Ability Test (GAT)",
        "url": "https://www.shl.com/products/product-catalog/view/general-ability-test/",
        "test_types": ["A"],
        "test_type": "A",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Measures general cognitive ability across numerical, verbal, and abstract reasoning domains. Suitable for a wide range of job levels.",
        "job_levels": ["Entry-Level", "Graduate", "Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Business", "Clerical"],
        "keywords": ["general ability", "cognitive", "numerical", "verbal", "abstract", "aptitude"],
    },
    {
        "name": "Financial Accounting (New)",
        "url": "https://www.shl.com/products/product-catalog/view/financial-accounting-new/",
        "test_types": ["K"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Multi-choice test measuring knowledge of financial accounting principles, statements, and standards.",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "job_families": ["Business"],
        "keywords": ["finance", "accounting", "financial statements", "GAAP", "accountant", "CPA"],
    },
    {
        "name": "Strategic Thinking",
        "url": "https://www.shl.com/products/product-catalog/view/strategic-thinking/",
        "test_types": ["A", "C"],
        "test_type": "A",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Measures ability to analyze complex business scenarios and make strategic decisions. Suitable for senior and executive roles.",
        "job_levels": ["Director", "Executive", "Manager"],
        "job_families": ["Business"],
        "keywords": ["strategy", "strategic thinking", "executive", "leadership", "business analysis", "decision making"],
    },
    # HR/Management
    {
        "name": "Leadership 360",
        "url": "https://www.shl.com/products/product-catalog/view/leadership-360/",
        "test_types": ["D"],
        "test_type": "D",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "360-degree feedback tool measuring leadership competencies from multiple rater perspectives.",
        "job_levels": ["Director", "Executive", "Manager"],
        "job_families": ["Business"],
        "keywords": ["leadership", "360", "development", "feedback", "management", "executive"],
    },
    {
        "name": "Personnel Reaction Blank (PRB)",
        "url": "https://www.shl.com/products/product-catalog/view/personnel-reaction-blank/",
        "test_types": ["B"],
        "test_type": "B",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Measures integrity and reliability through biodata questions predicting counterproductive work behavior.",
        "job_levels": ["Entry-Level", "Front Line Manager", "General Population"],
        "job_families": ["Business", "Clerical"],
        "keywords": ["integrity", "reliability", "biodata", "counterproductive", "honesty", "trustworthiness"],
    },
    # Contact Center specific
    {
        "name": "Customer Service Skills Simulation",
        "url": "https://www.shl.com/products/product-catalog/view/customer-service-skills-simulation/",
        "test_types": ["S"],
        "test_type": "S",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Realistic simulation of customer service tasks measuring multi-tasking, data accuracy, and customer interaction quality.",
        "job_levels": ["Entry-Level", "Mid-Professional"],
        "job_families": ["Contact Center", "Customer Service"],
        "keywords": ["customer service", "simulation", "contact center", "CX", "multi-tasking", "data entry"],
    },
    {
        "name": "Typing Skills Assessment",
        "url": "https://www.shl.com/products/product-catalog/view/typing-skills-assessment/",
        "test_types": ["K", "S"],
        "test_type": "K",
        "remote_testing": True,
        "adaptive_irt": False,
        "description": "Measures typing speed and accuracy relevant to data entry and administrative roles.",
        "job_levels": ["Entry-Level", "General Population"],
        "job_families": ["Clerical", "Contact Center"],
        "keywords": ["typing", "data entry", "speed", "accuracy", "clerical", "admin", "keyboard"],
    },
]


def get_catalog():
    """Return the full catalog."""
    return CATALOG


def get_catalog_by_url():
    """Return catalog as dict keyed by URL."""
    return {item["url"]: item for item in CATALOG}
